---
title: "Binary function transfer analyses"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
input_shareds = c("False")#, "True")
t1s = c("XOR_of_XORs", "XAO", "XOR", "AND")
t2s = c("X0", "XOR", "XOR_of_XORs", "XAO", "OR", "AND", "None")
lrs = c(0.005, 0.001)
nhs = c(10)
ims = c(1.)
num_runs = 10
directory_format = "results_second_train_both_nh_%i_lr_%.4f_im_%.2f/"

d = data.frame()
for (run in 0:(num_runs-1)) {
  for (input_shared in input_shareds) {
    for (num_hidden in nhs) {
      for (lr in lrs) {
        for (init_mult in ims) {
          directory = sprintf(directory_format, num_hidden, lr, init_mult)
          for (t1 in t1s) {
            for (t2 in t2s) {
            
              filename = sprintf("%st1%s_t2%s_sharedinput%s_run%i.csv", directory, t1, t2, input_shared, run)
              if (!file.exists(filename)) {
                next
              }
              this_d = tryCatch(read.csv(filename, header=T),
                                error = function(cond) {return(NA)})
              if (length(this_d) == 1 && is.na(this_d)) {
                next
              }
              this_d$num_hidden = num_hidden
              this_d$lr = lr
              this_d$init_size = init_mult
              this_d$t2 = ifelse(t2 == "parity", "5-parity", t2)
              this_d$run = run
              this_d$t1 = ifelse(t1 == "parity", "5-parity", t1)
              this_d$input_shared = input_shared
              d = bind_rows(d, this_d)
            }
          } 
        }
      }
    }
  }
}
```

```{r}
intermediate_d =d %>% 
  complete(epoch, nesting(num_hidden, init_size, lr, t1, t2, input_shared, run)) %>%
  group_by(num_hidden, init_size, lr, t1, t2, input_shared, run) %>%
  mutate(loss1 = ifelse(is.na(loss1) & epoch > 20000, min(loss1, na.rm=T), loss1),
         loss2 = ifelse(is.na(loss2) & epoch > 20000, min(loss2, na.rm=T), loss2),
         successful_learning_2 = any(loss2 < 0.05, na.rm=T),
         successful_learning_1 = any(loss1 < 0.05, na.rm=T),
         successful_learning = successful_learning_1 & successful_learning_2) %>%
  ungroup() 

summarized_d = intermediate_d %>%
  filter(successful_learning) %>%
  group_by(lr, num_hidden, init_size, t1, t2, input_shared, epoch) %>%
  summarize(sd_loss1 = sd(loss1),
            median_loss1 = median(loss1),
            loss1 = mean(loss1),
            sd_loss2 = sd(loss2),
            median_loss2 = median(loss2),
            loss2 = mean(loss2)) %>%
  ungroup()

success_d =  intermediate_d %>%
  filter(epoch==0) %>%
  group_by(lr, num_hidden, init_size, t1, t2, input_shared) %>%
  summarize(success_pct = sum(successful_learning)/n(),
            success_1_pct = sum(successful_learning_1)/n()) %>%
  ungroup()

intermediate_d = NA # get that out of memory

partly_more_summarized_d = d %>%
  group_by(num_hidden, init_size, lr, t1, t2, input_shared, run) %>%
  mutate(successful_learning_2 = any(loss2 < 0.05, na.rm=T),
         successful_learning_1 = any(loss1 < 0.05, na.rm=T),
         successful_learning = successful_learning_1 & successful_learning_2) %>%
  ungroup() %>%
  filter(successful_learning, loss1 < 0.05) %>%
  group_by(lr, num_hidden, init_size, t1, t2, input_shared, run) %>%
  summarize(epoch_001 = head(epoch-20000, 1)) %>%
  ungroup()

more_summarized_d = partly_more_summarized_d %>%
  group_by(lr, num_hidden, init_size, t1, t2, input_shared) %>%
  summarize(median_epoch_001 = median(epoch_001))
```

```{r}
theme_set(theme_bw())
```

```{r}
# t1s = c("5-parity", "XOR_of_XORs", "XOR", "AND")
# for (this_t1 in t1s) {
#   upper_lim = NA
#   ggplot(summarized_d %>% filter(t1 == this_t1), aes(x=epoch-20000, y=loss1, color=t2)) + 
#   #  geom_line(aes(group=interaction(run,t2)), data=d, alpha=0.1) +
#     geom_line(size=1.2) +
#     xlim(0, upper_lim) +
#     labs(x="epoch") +
#     facet_wrap( ~ input_shared)
#   #ggsave(sprintf("results_%s_smallweights.png", this_t1))
#   
#   ggplot(summarized_d %>% filter(t1 == this_t1), aes(x=epoch-20000, y=median_loss1, color=t2)) + 
#   #  geom_line(aes(y=loss1, group=interaction(run,t2)), data=d, alpha=0.1)+
#     geom_line(size=1.2) +
#    xlim(0, upper_lim) +
#     labs(x="epoch") +
#     facet_wrap( ~ input_shared)
#   #ggsave(sprintf("median_results_%s_smallweights.png", this_t1))
#   
# } 
```

```{r}
ggplot(success_d, aes(x=t1, y=success_1_pct, fill=t2)) +
  geom_bar(stat="identity", position="dodge") +
  scale_color_brewer(palette="Dark2")+
  facet_grid(num_hidden + init_size ~ lr, scales="free_y")
#ggsave("plots/success_results.png")
```

```{r}
ggplot(more_summarized_d %>% filter(lr == 0.005, num_hidden==10, init_size==0.33), aes(x=t1, y=median_epoch_001, color=t2)) +
  geom_point(size=1.5) + 
  facet_wrap(~ input_shared) +
  labs(x = "Task 1", y= "Median epoch when loss < 0.05") +
  scale_color_brewer(palette="Dark2") +
  facet_grid(num_hidden + init_size + t1 ~ lr, scales="free_y")
#ggsave("plots/median_results_summary.png")
```

```{r}
for (this_t1 in c("XOR", "XOR_of_XORs", "XAO", "AND")) {
  ggplot(partly_more_summarized_d %>% filter(lr == 0.005, num_hidden==10, init_size==0.33, t1==this_t1),
         aes(x=epoch_001, color=t2)) +
    geom_density() +
    geom_vline(data=more_summarized_d %>% ungroup() %>% filter(lr == 0.005, num_hidden==10, init_size==0.33, t1==this_t1),
               aes(xintercept=median_epoch_001, color=t2), linetype=2) +
    facet_grid(t2~.) +
    theme(panel.grid=element_blank()) +
    labs(x=sprintf("Epoch when %s loss < 0.001", this_t1)) +
    guides(color=guide_legend(title="Prior task"))
#  ggsave(sprintf("plots/%s_stopping_by_t2_distributions.png", this_t1), width=7, height=10)
}
```

```{r}
for (this_t1 in c("XOR", "XOR_of_XORs", "XAO", "AND")) {
  ggplot(partly_more_summarized_d %>% filter(lr == 0.005, num_hidden==10, init_size==1, t1==this_t1),
         aes(x=epoch_001, color=t2)) +
    geom_density() +
    geom_vline(data=more_summarized_d %>% ungroup() %>% filter(lr == 0.005, num_hidden==10, init_size==1., t1==this_t1),
               aes(xintercept=median_epoch_001, color=t2), linetype=2) +
    facet_grid(t2~.) +
    theme(panel.grid=element_blank()) +
    labs(x=sprintf("Epoch when %s loss < 0.001", this_t1)) +
    guides(color=guide_legend(title="Prior task"))
#  ggsave(sprintf("plots/%s_stopping_by_t2_distributions_large_weights.png", this_t1), width=7, height=10)
  ggsave(sprintf("plots/%s_stopping_by_t2_distributions_second_train_both.png", this_t1), width=7, height=10)
}
```

```{r}
partly_more_summarized_d %>% 
  filter(lr == 0.005, num_hidden==10, init_size==0.33, t2=="None") %>%
  arrange(epoch_001) %>%
  head()
```

