---
title: "Meta analyses (lol)"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
theme_set(theme_bw() +
            theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
```

```{r}
meta_mapping_tasks = c("ID", "NOT")
meta_classification_tasks = c("isX0", "isNOTX0", "isAND", "isOR", "isNOTAND", "isXOR", "isNOTXOR")
truly_new_tasks = c("NOTOR")
nruns = 20
m2ls = c("True", "False")
```

```{r}
d = data.frame()
for (m2l in m2ls) {
  for (run_i in 0:(nruns-1)) {
    filename = sprintf("meta_results/m2l%s_run%i_new_new_losses.csv", m2l, run_i)
    if (!file.exists(filename)) {
      next
    }
    this_d = read.csv(filename, header=T)
    this_d$run = run_i
    this_d$m2l = m2l
    this_d = this_d %>% 
      select(run, epoch, m2l, contains("new")) %>%
      gather(new_task, loss, contains("new")) %>%
      mutate(new_task=gsub("\\..*","",new_task))
  
    d = bind_rows(d, this_d)
  }
}
```

```{r}
task_truly_new =  function(tasks) {
  return(any(vapply(truly_new_tasks, function(x) grepl(x, tasks), T)))
} 
task_truly_new = Vectorize(task_truly_new)
```

```{r}
d = d %>%
  mutate(condition = ifelse(task_truly_new(new_task), "Completely new", "New application"))
```


```{r}
guess_summarized_d = d %>%
  group_by(new_task, condition, m2l, run) %>%
  summarize(guess = head(loss, 1),
            trained = tail(loss, 1)) %>%
  ungroup() %>%
  gather(type, loss, guess, trained) %>%
  group_by(new_task, condition, m2l, type) %>%
  summarize(loss_sd = sd(loss),
            loss = mean(loss),
            loss_ci_lo = loss - 1.96 * loss_sd/sqrt(n()),
            loss_ci_hi = loss + 1.96 * loss_sd/sqrt(n())) %>%
  ungroup() %>%
  mutate(type=factor(type,
                     levels=c("guess", "trained")))
```

```{r}
ggplot(data=guess_summarized_d %>% filter(!(new_task %in% c("X0")), type == "guess"), aes(x=new_task, y=loss, fill=condition)) +
  geom_bar(stat="identity", position="dodge") + 
  geom_errorbar(aes(ymin=loss_ci_lo, ymax=loss_ci_hi), position="dodge", width=0.5) +
  scale_fill_brewer(palette="Dark2") +
  labs(x="New task", y="Proportion wrong") +
  ylim(0, 1) +
  geom_hline(yintercept=0.5, alpha=0.5, linetype=2) +
  facet_grid(.~m2l)
```
```{r}
ggsave("plots/meta/meta_res.png")
```
```{r}
ggplot(data=guess_summarized_d %>% filter(!(new_task %in% c("X0")), type == "trained"), aes(x=new_task, y=loss, fill=condition)) +
  geom_bar(stat="identity", position="dodge") + 
  geom_errorbar(aes(ymin=loss_ci_lo, ymax=loss_ci_hi), position="dodge", width=0.5) +
  scale_fill_brewer(palette="Dark2") +
  labs(x="New task", y="Proportion wrong") +
  ylim(0, 1) +
  geom_hline(yintercept=0.5, alpha=0.5, linetype=2) +
  facet_grid( .  ~ m2l)
```
```{r}
ggsave("plots/meta/meta_res_final.png")
```
# embeddings

```{r}
for (emb_type in c("guess", "final")) {
  for (m2l in m2ls) {
    emb_d = data.frame()
    for (run_i in 0:(nruns-1)) {
      filename = sprintf("meta_results/m2l%s_run%i_%s_embeddings.csv", m2l, run_i, emb_type)
      if (!file.exists(filename)) {
        next
      }
      this_d = read.csv(filename, header=T)
      this_d$run = run_i
      emb_d = bind_rows(emb_d, this_d)
    }
    pcs = prcomp(emb_d %>% select(-dimension, -run, -one_of(meta_mapping_tasks), -one_of(meta_classification_tasks)), center=T, scale=T)
    pc_d = data.frame(pcs$rotation)
    pc_d$task = row.names(pc_d)
    ggplot(pc_d, aes(x=PC1, y=PC2, color=task)) +
      geom_point() +
      geom_text(aes(label=task)) 
    ggsave(sprintf("plots/meta/PCA_m2l%s_%s.png", m2l, emb_type), width=20, height=7)
    pcs = prcomp(emb_d %>% select(-dimension, -run), center=T, scale=T)
    pc_d = data.frame(pcs$rotation)
    pc_d$task = row.names(pc_d)
    ggplot(pc_d, aes(x=PC1, y=PC2, color=task)) +
      geom_point() +
      geom_text(aes(label=task)) 
    ggsave(sprintf("plots/meta/PCA_full_m2l%s_%s.png", m2l, emb_type), width=20, height=7)
  }
}
```

```{r}
emb_type = "guess"
emb_d = data.frame()
for (m2l in m2ls) {
  for (meta_task in c("None", meta_mapping_tasks)) {
    for (run_i in 0:(nruns-1)) {
      if (meta_task == "None") {
        filename = sprintf("meta_results/m2l%s_run%i_%s_embeddings.csv", m2l, run_i, emb_type)
        if (!file.exists(filename)) {
          next 
        }
        this_d = read.csv(filename, header=T)
      } else {
        filename = sprintf("meta_results/m2l%s_run%i_%s_%s_embeddings.csv", m2l, run_i, meta_task, emb_type)
        if (!file.exists(filename)) {
          next 
        }
        this_d = read.csv(filename, header=T)
      }
      this_d$run = run_i
      this_d$m2l = m2l
      this_d$meta_task = meta_task
      emb_d = bind_rows(emb_d, this_d)
    }
  }
}
```

```{r}
emb_mappings = c("None", "NOT", "ID")
emb_classifications =  c("isAND", "isXOR", "isX0")
emb_mappings_mapped =  c("NOT", "ID")
emb_dist_d = data.frame()
for (this_m2l in m2ls) {
  for (run_i in unique(emb_d$run)) {
    emb_matrix = emb_d %>%
      filter(run == run_i,
             m2l == this_m2l) %>% 
      select(-run, -m2l) %>%
      gather(task, value, -c(dimension, meta_task)) %>%
      unite(meta_and_task, meta_task, task) %>%
      spread(meta_and_task, value) %>%
      select(-dimension) %>%
      as.matrix(.) # %>%
      # t(.) %>%
      # dist(.) %>% 
      # as.matrix(.)
    
    nrows = dim(emb_matrix)[1]
    ncols = dim(emb_matrix)[2]
    emb_matrix = emb_matrix * matrix(rep(1/sqrt(colSums(emb_matrix^2)), each=nrows), nrow=nrows, ncol=ncols)
    
    emb_dist_matrix = t(emb_matrix) %*% emb_matrix
    
    for (mapped in meta_classification_tasks) {
      for (mapping in c("None", meta_mapping_tasks)) {
        this_d = as.data.frame(emb_dist_matrix[paste(mapping, mapped, sep="_"), c("None_NOT", "None_ID", "None_isAND", "None_isNOTAND", "None_isNOTX0", "None_isX0", "None_isXOR", "None_isNOTXOR", "None_isOR")])
        names(this_d) = c("distance")
        this_d$mapping = mapping
        this_d$mapped_task = mapped
        this_d$run = run_i
        this_d$m2l = this_m2l
        this_d$target =row.names(this_d)
        emb_dist_d = bind_rows(emb_dist_d, this_d)
      }
    }
    
    for (mapped in emb_mappings_mapped) {
      for (mapping in c("None", meta_mapping_tasks)) {
        this_d = as.data.frame(emb_dist_matrix[paste(mapping, mapped, sep="_"), c("None_ID", "None_NOT", "ID_ID", "ID_NOT", "NOT_ID", "NOT_NOT")])
        names(this_d) = c("distance")
        this_d$mapped_task = mapped
        this_d$mapping = mapping
        this_d$run = run_i
        this_d$m2l = this_m2l
        this_d$target =row.names(this_d)
        emb_dist_d = bind_rows(emb_dist_d, this_d)
      }
    }
  }
}
```

```{r}
emb_dist_diff_d = emb_dist_d %>% 
  spread(mapping, distance) %>%
  mutate(delta_NOT = NOT-None,
         delta_ID = ID-None,
         delta_NOT_ID = NOT-ID) %>%
  group_by(m2l, mapped_task, target) %>%
  summarize(NOT = mean(NOT),
            delta_NOT = mean(delta_NOT),
            delta_ID= mean(delta_ID),
            delta_NOT_ID = mean(delta_NOT_ID))
```

```{r}
ggplot(emb_dist_diff_d %>% filter(mapped_task %in% emb_classifications),
       aes(x=target, fill=target, y=delta_NOT)) +
  geom_bar(stat="identity") +
  facet_grid(m2l~mapped_task)
```

```{r}
 ggplot(emb_dist_d %>% filter(mapped_task %in% emb_mappings_mapped,
                              target %in% c("NOT_ID", "NOT_NOT")) %>%
          group_by(m2l, mapping, mapped_task, target) %>%
          summarize(se=sd(distance)/sqrt(n()),
                    distance=mean(distance),
                    ci_lo=distance - 1.96 * se,
                    ci_hi=distance + 1.96 * se),
        aes(x=target, fill=target, y=distance)) +
   geom_bar(stat="identity") +
   geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi), width = 0.25) +
   facet_grid(m2l~  mapping + mapped_task)
```

# meta-tasks


```{r}
meta_d = data.frame()
for (m2l in m2ls) {
  for (run_i in 0:(nruns-1)) {
    filename = sprintf("meta_results/m2l%s_run%i_new_meta_true_losses.csv", m2l, run_i)
    if (!file.exists(filename)) {
      next 
    }    
    this_d = read.csv(filename, header=T)
    this_d$run = run_i
    this_d$m2l = m2l
    this_d = this_d %>% 
      gather(mapping, loss, -c(run, m2l, epoch)) %>%
      mutate(is_new = grepl("new", mapping),
             is_truly_new = task_truly_new(mapping),
             condition = ifelse(is_truly_new, "completely_new",
                         ifelse(is_new, "new_application",
                                "old"))) %>%
      separate(mapping, c("meta_task", "original_task", "relevant"), sep="\\.", extra="drop")
  
    meta_d = bind_rows(meta_d, this_d)
  }
}
```

```{r}
meta_bookend_summarized_d = meta_d %>%
#  filter(original_task != "XOR") %>%
  group_by(run, m2l) %>%
  filter(epoch == 0 | epoch == max(epoch)) %>%
  ungroup() %>%
  mutate(time=ifelse(epoch==0, "guess", "final")) %>%
  select(-epoch) %>%
  group_by(time, m2l, meta_task, condition) %>%
  summarize(mean_loss = mean(loss),
            se_loss = sd(loss)/sqrt(n())) %>%
  ungroup() %>%
  mutate(cihi=mean_loss + 1.96*se_loss, 
         cilo=mean_loss - 1.96*se_loss)
```

```{r}
ggplot(data=meta_bookend_summarized_d %>% filter(time=="guess"), aes(x=meta_task, fill=condition, y=mean_loss)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin=cilo, ymax=cihi), position="dodge") +
  scale_fill_brewer(palette="Dark2") +
  labs(x="New task", y="Mean proportion wrong") +
  ylim(0, 1) +
  geom_hline(yintercept=0.5, alpha=0.5, linetype=2) +
  facet_grid(. ~ m2l)
```

```{r}
ggsave("plots/meta/meta_guess_performance_summarized.png")
```

```{r}
meta_bookend_d = meta_d %>%
  group_by(run, m2l) %>%
  filter(epoch == 0 | epoch == max(epoch)) %>%
  ungroup() %>%
  mutate(time=ifelse(epoch==0, "guess", "final")) %>%
  select(-epoch) %>%
  group_by(m2l, time, meta_task, original_task, condition) %>%
  summarize(mean_loss = mean(loss),
            se_loss = sd(loss)/sqrt(n())) %>%
  ungroup() %>%
  mutate(cihi=mean_loss + 1.96*se_loss, 
         cilo=mean_loss - 1.96*se_loss)
```

```{r}
ggplot(data=meta_bookend_d %>% filter(time=="guess"), aes(x=original_task, fill=condition, y=mean_loss)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin=cilo, ymax=cihi), position="dodge") +
  scale_fill_brewer(palette="Dark2") +
  geom_hline(yintercept=0.5, alpha=0.5, linetype=2) +
  labs(x="New task", y="Proportion wrong") +
  facet_grid(m2l ~ meta_task) + 
  ylim(0, 1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggsave("plots/meta/meta_guess_performance.png")
```

