---
title: "Binary function transfer analyses"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
input_shareds = c("False")#, "True")
t1s = c("0", "1")
t2s = c("0", "1", "None")
nt2s = c(1, 2, 3, 4)
lrs = c(1e-4)
nls = c(5) #, 7)
nhs = c(50)
ims = c(0.033) #, 0.1)
gthls = c(2) #, 4, 6) 
gtbs = c(5)
optimizer = "Adam"
num_runs = 500
directory_format = "results_moretask_separateseed_generalization_nonbinary_scales_%s_stb_nt2_%i_gthl_%i_gtb_%i_nse_4400_nte_800_nl_%i_nh_%i_lr_%.4f_im_%.2f/"

d = replicate(num_runs * length(lrs) * length(nhs) * length(t1s) * length(t2s) * length(input_shareds) * length(nt2s) * length(nls) * length(ims) * length(gthls) * length(gtbs),
              data.frame())
index = 1
for (run in 0:(num_runs-1)) {
  for (input_shared in input_shareds) {
    for (num_layers in nls) {
      for (ground_truth_hidden_layers in gthls) {
        for (ground_truth_bottleneck in gtbs) {
          for (num_prior_tasks in nt2s) {
            for (num_hidden in nhs) {
              for (lr in lrs) {
                for (init_mult in ims) {
                  directory = sprintf(directory_format, optimizer, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, lr, init_mult)
                  for (t1 in t1s) {
                    for (t2 in t2s) {
                      filename = sprintf("%st1%s_t2%s_sharedinput%s_run%i.csv", directory, t1, t2, input_shared, run)
                      if (!file.exists(filename)) {
                        next
                      }
                      this_d = tryCatch(read.csv(filename, header=T),
                                        error = function(cond) {return(NA)})
                      if (length(this_d) == 1 && is.na(this_d)) {
                        next
                      }
                      this_d$num_prior_tasks = num_prior_tasks
                      this_d$num_hidden = num_hidden
                      this_d$num_layers = num_layers
                      this_d$ground_truth_bottleneck = ground_truth_bottleneck
                      this_d$ground_truth_hidden_layers = ground_truth_hidden_layers
                      this_d$lr = lr
                      this_d$init_size = init_mult
                      this_d$t2 = ifelse(t2 == "parity", "5-parity", t2)
                      this_d$run = run
                      this_d$t1 = ifelse(t1 == "parity", "5-parity", t1)
                      this_d$input_shared = input_shared
                      d[[index]] = this_d
                      index = index + 1
                    }
                  } 
                }
              }
            }
          }
        }
      }
    }
  }
}

d = bind_rows(d)
```

```{r}
d_2 = d %>%
  rename(loss1_train=loss1) %>%
  select(-starts_with("loss2")) %>%
  gather(loss_name, loss_value, starts_with("loss")) %>%
  separate(loss_name, c("task_domain", "train_or_test")) %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run, task_domain, train_or_test) %>%
  mutate(loss_value = loss_value/head(loss_value, n=1)) %>% # normalize by first value
  ungroup() %>%
  spread(train_or_test, loss_value) 

```


# old slow analyses

```{r}
# intermediate_d =d %>% 
#   rename(loss1_train=loss1,
#          loss2_train=loss2) %>%
#   complete(epoch, nesting(num_hidden, init_size, lr, t1, t2, input_shared, run)) %>%
#   gather(loss_name, loss_value, starts_with("loss")) %>%
#   separate(loss_name, c("task_domain", "train_or_test")) %>%
#   group_by(num_hidden, init_size, lr, t1, t2, input_shared, run, task_domain, train_or_test) %>%
#   mutate(loss_value = ifelse(is.na(loss_value), min(loss_value, na.rm=T), loss_value)) %>%
#   ungroup() %>%
#   spread(train_or_test, loss_value) %>%
#   group_by(num_hidden, init_size, lr, t1, t2, input_shared, run, task_domain) %>%
#   mutate(successful_learning_domain = any(train < 0.05)) %>%
#   ungroup() %>%
#   group_by(num_hidden, init_size, lr, t1, t2, input_shared, run, task_domain) %>%
#   mutate(successful_learning = all(successful_learning_domain)) %>%
#   ungroup() %>%
#   mutate(rescaled_epoch = ifelse(epoch < 20000, epoch, epoch-20000))
#   
# 
# summarized_d = intermediate_d %>%
#   filter(successful_learning) %>%
#   group_by(lr, num_hidden, init_size, t1, t2, input_shared, epoch, task_domain) %>%
#   summarize(sd_train = sd(train),
#             median_train = median(train),
#             train = mean(train),
#             sd_test = sd(test),
#             median_test = median(test),
#             test = mean(test)) %>%
#   ungroup()
# 
# partly_more_summarized_d = intermediate_d %>%
#   filter(successful_learning, task_domain == "loss1", train < 0.05) %>%
#   group_by(lr, num_hidden, init_size, t1, t2, input_shared, run) %>%
#   summarize(epoch_001 = head(epoch-20000, 1)) %>%
#   ungroup()
# 
# more_summarized_d = partly_more_summarized_d %>%
#   group_by(lr, num_hidden, init_size, t1, t2, input_shared) %>%
#   summarize(median_epoch_001 = median(epoch_001))
# 
# successful_generalization_d = intermediate_d %>%
#   filter(successful_learning, task_domain=="loss1", test < 0.05) %>%
#   group_by(lr, num_hidden, init_size, t1, t2, input_shared, run) %>%
#   summarize(epoch_005 = head(epoch, 1)) %>%
#   ungroup()
#   
  
```


```{r}
# ggplot(intermediate_d %>%
#          filter(task_domain == "loss1",
#                 epoch >= 40000),
#        aes(x=rescaled_epoch, y=test, color=t2)) +
#   geom_line(stat="summary",
#             fun.y="mean") +
#   facet_wrap(~t1, scales="free")
```

# efficient analyses

These are more efficient to compute with really large datasets.
```{r}
success_pct = 0.1  # what percent of the original test error you must reach to be considered a success

training_succeeds = d_2 %>% 
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run) %>% 
  summarize(successful_learning_target = any(task_domain == "loss1" & train < 0.01)) %>% 
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared) %>% 
  summarize(pct_successful_learning_target = mean(successful_learning_target, na.rm=T)) %>% 
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Nonisomorphic")) %>%
  arrange(pct_successful_learning_target)

min_generalization_d_2 = d_2 %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run) %>%
  mutate(successful_learning_source = any(task_domain=="loss2" & test < success_pct)) %>%
  ungroup() %>%
  filter(task_domain == "loss1") %>%
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Nonisomorphic")) %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, prior_task, input_shared, run, successful_learning_source) %>%
  summarize(min_gen_target = min(test)) %>%
  ungroup() 

min_generalization_difference_d_2 = d_2 %>%
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Nonisomorphic")) %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, prior_task, input_shared, run, task_domain) %>%
  summarize(min_gen = min(test)) %>%
  ungroup() %>%
  spread(task_domain, min_gen) %>%
  rename(min_gen_target = loss1) %>%
         #min_gen_source = loss2) %>%
  #mutate(min_gen_source = ifelse(prior_task == "None", 0, min_gen_source)) %>%
  gather(measurement, value, starts_with("min_gen")) %>%
  unite(prior_and_measurement, prior_task, measurement) %>%
  select(-t2) %>%
  spread(prior_and_measurement, value) %>%
  mutate(iso_vs_noniso = Isomorphic_min_gen_target - Nonisomorphic_min_gen_target,
         iso_vs_none = Isomorphic_min_gen_target - None_min_gen_target)

successful_generalization_d_2 = d_2 %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run, task_domain) %>%
  top_n(1, wt=epoch) %>% 
  ungroup() %>%
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Nonisomorphic")) %>%
  group_by(lr, num_prior_tasks, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, prior_task, input_shared, run) %>%
  summarize(successful_learning_source = any(task_domain=="loss2" & test < success_pct),
            successful_learning_target = any(task_domain=="loss1" & epoch >= 10000 & test < success_pct)) %>%
  ungroup()
  
stopping_d_2 = d_2 %>%
#  filter(test < success_pct) %>% # only take runs where something was successfully generalized
  group_by(lr, num_prior_tasks, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run, task_domain) %>%
  top_n(1, wt=epoch) %>% 
  ungroup() %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run) %>%
  mutate(successful_learning_source = any(task_domain=="loss2")) %>%
  ungroup() %>%
  filter(task_domain == "loss1" & epoch > 10000) %>%
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Non-isomorphic")) %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, prior_task, input_shared, successful_learning_source, run) %>% 
  summarize(epoch_success = min(epoch))
```

```{r}
theme_set(theme_bw())

```

```{r}
ggplot(training_succeeds, # %>% filter(prior_task != "None"),
       aes(x=prior_task, y=pct_successful_learning_target, fill=prior_task)) +
  geom_bar(stat="summary",
             fun.y="mean") +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_boot",
                width=0.25) +
  scale_color_brewer(palette="Dark2") +
  labs(x="Prior task", y="% successful learning") +
  guides(fill=guide_legend(title="Prior task")) +
  facet_grid(num_layers + num_hidden ~ num_prior_tasks + ground_truth_hidden_layers + init_size)
```


```{r}
ggplot(min_generalization_d_2, # %>% filter(prior_task != "None"),
       aes(x=prior_task, y=min_gen_target, color=prior_task)) +
  geom_point(stat="summary",
           fun.y="mean") +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_boot",
                position=position_dodge(0.9),
                width=0.25) +
  scale_color_brewer(palette="Dark2") +
  labs(x="Prior task", y="Avg. optimal test error") +
  guides(fill=guide_legend(title="Prior task")) +
  facet_grid(num_layers + num_hidden  ~ num_prior_tasks + ground_truth_hidden_layers  + init_size)
#ggsave("plots/transfer_nonbinary_tasks.png", width=6, height=4)
```

```{r}
ggplot(min_generalization_difference_d_2, aes(x=iso_vs_noniso)) +
  geom_density() +
  geom_vline(data=min_generalization_difference_d_2 %>%
               group_by(lr, ground_truth_bottleneck, ground_truth_hidden_layers, num_layers, num_hidden, init_size, input_shared) %>%
               summarize(iso_vs_noniso_mean = mean(iso_vs_noniso, na.rm=T)) %>%
               ungroup(),
             mapping=aes(xintercept=iso_vs_noniso_mean),
             stat = "summary",
             fun.x = "mean") +
  geom_vline(xintercept=0,
             color="red",
             linetype=2) +
  labs(x="", y="Density") +
  facet_grid(num_layers + num_hidden ~ num_prior_tasks + ground_truth_hidden_layers + init_size)
#ggsave("plots/nonbinary_min_gen_difference.png", width=6, height=4)
```


```{r}
ggplot(min_generalization_difference_d_2, aes(x=None_min_gen_target, y=iso_vs_noniso)) +
  geom_point() +
  geom_hline(yintercept=0,
             color="red",
             linetype=2) +
  geom_smooth(method="lm") +
  labs(x="Generalization error (No prior task)", y="Iso gen - noniso gen") +
  facet_grid(num_layers  + num_hidden~ num_prior_tasks + ground_truth_hidden_layers + init_size, scales="free")
#ggsave("plots/nonbinary_min_gen_difference_iso_noniso_num_prior.png", width=9, height=6)
```

```{r}
ggplot(min_generalization_difference_d_2, aes(x=iso_vs_none)) +
  geom_density() +
  geom_vline(data=min_generalization_difference_d_2 %>%
               group_by(lr, ground_truth_bottleneck, ground_truth_hidden_layers, num_layers, num_hidden, init_size, input_shared) %>%
               summarize(iso_vs_none_mean = mean(iso_vs_none, na.rm=T)) %>%
               ungroup(),
             mapping=aes(xintercept=iso_vs_none_mean),
             stat = "summary",
             fun.x = "mean") +
  geom_vline(xintercept=0,
             color="red",
             linetype=2) +
  labs(x="Iso - None", y="Density") +
  facet_grid(num_layers + num_hidden~ num_prior_tasks + ground_truth_hidden_layers  + init_size)
#ggsave("plots/nonbinary_min_gen_difference_iso_noniso_simple.png", width=9, height=6)
```

```{r}
ggplot(min_generalization_difference_d_2, aes(x=None_min_gen_target, y=iso_vs_none)) +
  geom_point() +
  geom_hline(yintercept=0,
             color="red",
             linetype=2) +
  geom_smooth(method="lm") +
  labs(x="Generalization error (no prior task)", y="Iso gen - None gen") +
  facet_grid(num_layers+ num_hidden ~ num_prior_tasks + ground_truth_hidden_layers + init_size)
#ggsave("plots/nonbinary_min_gen_difference_iso_none.png", width=9, height=6)
```

```{r}
ggplot(stopping_d_2, aes(x=prior_task, y=epoch_success-10000, color=prior_task)) +
  geom_point(stat="summary",
           fun.y="mean",
           position=position_dodge(0.9)) +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_boot",
                position=position_dodge(0.9),
                width=0.25) +
  scale_color_brewer(palette="Dark2") +
  facet_grid(num_layers + num_hidden~ num_prior_tasks + ground_truth_hidden_layers  + init_size, scales="free")
#ggsave("plots/nonbinary_stopping_times.png", width=6, height=4)


```

# curves and area under them

```{r}
ggplot(d_2 %>% 
         filter(task_domain == "loss1",
                epoch >= 10000,
                ground_truth_hidden_layers == 2) %>%
         mutate(prior_task = case_when(t2 == "None" ~ "None",
                                       t2 == t1 ~ "Isomorphic",
                                       T ~ "Non-isomorphic")) %>%
         complete(epoch, nesting(lr, prior_task, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run)) %>%
         group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run) %>% 
         mutate(test = ifelse(is.na(test), min(test, na.rm=T), test)) %>%
         ungroup(), 
       aes(x=epoch - 10000, y=test, color=prior_task)) +
  geom_line(stat="summary",
            fun.y="mean") + 
  ylim(0, 0.25)
ggsave("plots/nonbinary_transfer_curves.png", width=6, height=4)
```

```{r}
integral_d = d_2 %>% 
  filter(task_domain == "loss1",
         epoch >= 10000) %>%
  mutate(prior_task = case_when(t2 == "None" ~ "None",
                                t2 == t1 ~ "Isomorphic",
                                T ~ "Non-isomorphic")) %>%
  complete(epoch, nesting(lr, prior_task, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, run)) %>%
  group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, t1, t2, input_shared, prior_task, run) %>% 
  mutate(test = ifelse(is.na(test), min(test, na.rm=T), test)) %>%
  summarize(test_integral = mean(test)) %>%
  ungroup()
         # group_by(lr, num_prior_tasks, ground_truth_hidden_layers, ground_truth_bottleneck, num_layers, num_hidden, init_size, input_shared, prior_task) %>% 
         # summarize(mean_test_integral = mean(test_integral))
        
```

```{r}
integral_diff_d = integral_d %>%
  select(-t2) %>%
  spread(prior_task, test_integral) %>%
  mutate(iso_vs_noniso = Isomorphic - `Non-isomorphic`,
         iso_vs_none = Isomorphic - None)
```

```{r}
ggplot(integral_diff_d, aes(x=None, y=iso_vs_noniso)) +
  geom_point() +
  geom_hline(yintercept=0,
             color="red",
             linetype=2) +
  geom_smooth(method="lm") +
  labs(x="Gen. Integral (No prior task)", y="Iso gen. int. - noniso gen. int.") +
  facet_grid(num_layers  + num_hidden~ num_prior_tasks + ground_truth_hidden_layers + init_size, scales="free")
#ggsave("plots/nonbinary_integral_differences.png")
```

